apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-backend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-backend
  template:
    metadata:
      labels:
        app: frontend-backend
    spec:
      containers:
        - name: frontend
          image: jadamaneddine/frontend:1.0
          ports:
            - containerPort: 80
        - name: backend
          image: jadamaneddine/backend:1.0
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-backend-service
spec:
  selector:
    app: frontend-backend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: backend
      protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort
