name: Docker Build and Push

on:
  push:
    branches:
      - main  # You can change this to your main branch name

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: jadamaneddine
        password: J@d76759501
        
    - name: Build and push frontend image
      run: |
        docker build -t jadamaneddine/frontend -f ./frontend/dockerfile .
        docker push jadamaneddine/frontend
    
    - name: Build and push backend image
      run: |
        docker build -t jadamaneddine/backend -f dockerfile.nodejs .
        docker push jadamaneddine/backend
