name: Enhanced Build and Push Docker Images

on:
  push:
    branches: [ imagedemo ] # Trigger on push to main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2 # Checks out your repository under $GITHUB_WORKSPACE

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }} # Use GitHub Secrets
        password: ${{ secrets.DOCKER_PASSWORD }} # Use GitHub Secrets

    - name: Build and push frontend Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:${{ github.sha }} ./frontend
        docker push ${{ secrets.DOCKER_USERNAME }}/frontend:${{ github.sha }}
      # Uses commit SHA for tagging, enhancing traceability

    - name: Build and push backend Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:${{ github.sha }} ./backend
        docker push ${{ secrets.DOCKER_USERNAME }}/backend:${{ github.sha }}
      # Uses commit SHA for tagging, enhancing traceability
